// Placeholder Firebase options. Replace with real config by running:
// flutter pub add flutterfire_cli (if needed) and flutterfire configure
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Replace this with platform-specific options generated by FlutterFire CLI.
    return const FirebaseOptions(
      apiKey: 'YOUR_API_KEY',
      appId: 'YOUR_APP_ID',
      messagingSenderId: 'YOUR_SENDER_ID',
      projectId: 'YOUR_PROJECT_ID',
    );
  }
}
